import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { BarChart3, BookOpen, CalendarDays, CreditCard, GraduationCap, LayoutDashboard, LogOut, Menu, Moon, Plus, Search, Sun, Users, UserRound, Wallet } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import api from './api';
import './styles.css';

const Auth = createContext(null);
const money = (value) => new Intl.NumberFormat('uz-UZ', { style: 'currency', currency: 'UZS', maximumFractionDigits: 0 }).format(value || 0);
const nav = [{to:'/',label:'Bosh sahifa',icon:LayoutDashboard},{to:'/students',label:'O‘quvchilar',icon:GraduationCap},{to:'/groups',label:'Guruhlar',icon:Users},{to:'/teachers',label:'O‘qituvchilar',icon:UserRound},{to:'/courses',label:'Kurslar',icon:BookOpen},{to:'/attendance',label:'Davomat',icon:CalendarDays},{to:'/payments',label:'To‘lovlar',icon:CreditCard},{to:'/expenses',label:'Xarajatlar',icon:Wallet},{to:'/reports',label:'Hisobotlar',icon:BarChart3}];

function Login(){ const {register,handleSubmit,formState:{errors}}=useForm(); const {login}=useContext(Auth); const [error,setError]=useState(''); const submit=async d=>{try{await login(d.username,d.password)}catch{setError('Email yoki parol noto‘g‘ri')}}; return <main className="login"><section><div className="brand"><GraduationCap/> Edu CRM</div><h1>Ta’lim markazingizni bir joydan boshqaring.</h1><p>O‘quvchilar, guruhlar, to‘lovlar va hisobotlar — hammasi tartibda.</p></section><form onSubmit={handleSubmit(submit)} className="login-card"><h2>Xush kelibsiz</h2><p>Tizimga kirish uchun ma’lumotlaringizni kiriting.</p>{error&&<div className="alert">{error}</div>}<label>Email<input {...register('username',{required:true})} type="email" placeholder="admin@educrm.uz"/></label><label>Parol<input {...register('password',{required:true})} type="password" placeholder="••••••••"/></label><button>Kirish</button><small>Demo: admin@educrm.uz / Admin123!</small></form></main> }

function Shell(){const {user,logout}=useContext(Auth); const [dark,setDark]=useState(false); const [open,setOpen]=useState(false); useEffect(()=>document.documentElement.dataset.theme=dark?'dark':'light',[dark]); return <div className="shell"><aside className={open?'open':''}><div className="logo"><GraduationCap/> <span>Edu CRM</span></div><div className="academy">Bilimdon Academy</div><nav>{nav.map(({to,label,icon:Icon})=><NavLink onClick={()=>setOpen(false)} key={to} to={to} end><Icon size={19}/>{label}</NavLink>)}</nav><div className="side-user"><div className="avatar">{user?.full_name?.[0]}</div><div><strong>{user?.full_name}</strong><small>{user?.role}</small></div><button title="Chiqish" onClick={logout}><LogOut size={18}/></button></div></aside><div className="content"><header><button className="menu" onClick={()=>setOpen(!open)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Qidirish..."/></div><div className="header-actions"><button onClick={()=>setDark(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><div className="avatar">{user?.full_name?.[0]}</div></div></header><main className="page"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/students" element={<Students/>}/><Route path="/groups" element={<ResourcePage title="Guruhlar" endpoint="groups" fields={[['name','Guruh nomi'],['course_id','Kurs ID','number'],['teacher_id','O‘qituvchi ID','number'],['monthly_fee','Oylik to‘lov','number'],['max_students','Maks. o‘quvchi','number']]}/>}/><Route path="/teachers" element={<ResourcePage title="O‘qituvchilar" endpoint="teachers" fields={[['first_name','Ism'],['last_name','Familiya'],['phone','Telefon'],['specialty','Mutaxassislik']]}/>}/><Route path="/courses" element={<ResourcePage title="Kurslar" endpoint="courses" fields={[['name','Kurs nomi'],['description','Tavsif'],['duration_months','Davomiylik (oy)','number'],['price','Narxi','number']]}/>}/><Route path="/attendance" element={<ResourcePage title="Davomat" endpoint="attendance" fields={[['group_id','Guruh ID','number'],['student_id','O‘quvchi ID','number'],['lesson_date','Sana','date'],['status','Holat (present/absent/late/excused)']]}/>}/><Route path="/payments" element={<Payments/>}/><Route path="/expenses" element={<ResourcePage title="Xarajatlar" endpoint="expenses" fields={[['name','Xarajat nomi'],['category','Kategoriya'],['amount','Summa','number'],['expense_date','Sana','date']]}/>}/><Route path="/reports" element={<Reports/>}/></Routes></main></div></div>}

function Dashboard(){const [data,setData]=useState(null); useEffect(()=>{api.get('/reports/dashboard').then(r=>setData(r.data))},[]); if(!data)return <Loading/>; const cards=[['Jami o‘quvchilar',data.total_students,GraduationCap,'blue'],['Faol o‘quvchilar',data.active_students,Users,'green'],['Faol guruhlar',data.active_groups,BookOpen,'violet'],['Oylik tushum',money(data.monthly_income),Wallet,'orange']]; const chart=[{n:'Tushum',v:Number(data.monthly_income)},{n:'Xarajat',v:Number(data.monthly_expenses)},{n:'Sof natija',v:Number(data.monthly_income)-Number(data.monthly_expenses)}]; return <><Title title="Bosh sahifa" text="Markazingizdagi bugungi holat"/><div className="cards">{cards.map(([l,v,I,c])=><article className="metric" key={l}><span className={c}><I/></span><div><small>{l}</small><strong>{v}</strong></div></article>)}</div><section className="grid"><article className="panel chart"><h3>Moliyaviy ko‘rsatkichlar</h3><ResponsiveContainer width="100%" height={260}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="n"/><YAxis/><Tooltip formatter={v=>money(v)}/><Bar dataKey="v" fill="#4867e8" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="panel"><h3>Tezkor ma’lumot</h3><dl><div><dt>Bugungi darslar</dt><dd>{data.today_lessons}</dd></div><div><dt>Qarzdorlik</dt><dd className="danger">{money(data.debt)}</dd></div><div><dt>Oylik xarajatlar</dt><dd>{money(data.monthly_expenses)}</dd></div></dl></article></section><section className="panel"><h3>So‘nggi qo‘shilgan o‘quvchilar</h3><DataTable items={data.recent_students} columns={['first_name','last_name','phone','status']}/></section></>}

function Students(){return <ResourcePage title="O‘quvchilar" endpoint="students" searchable fields={[['first_name','Ism'],['last_name','Familiya'],['phone','Telefon'],['guardian_name','Mas’ul shaxs'],['guardian_phone','Mas’ul telefon']]}/>}
function Payments(){return <ResourcePage title="To‘lovlar" endpoint="payments" fields={[['student_id','O‘quvchi ID','number'],['group_id','Guruh ID','number'],['amount','Summa','number'],['payment_date','Sana','date'],['period','To‘lov davri'],['method','Usul (cash/card/transfer)']]}/>}

function ResourcePage({title,endpoint,fields=[],searchable=false}){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[q,setQ]=useState(''),[error,setError]=useState(''); const load=async()=>{setLoading(true);try{const r=await api.get(`/${endpoint}`,{params:searchable&&q?{q}:undefined});setItems(r.data.items||[])}catch{setError('Ma’lumotlarni yuklab bo‘lmadi')}finally{setLoading(false)}};useEffect(()=>{load()},[q]);return <><Title title={title} text={`${title} ro‘yxatini boshqaring`} action={()=>setShow(true)}/>{searchable&&<div className="toolbar"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ism, familiya yoki telefon orqali qidirish"/></div>}{error&&<div className="alert">{error}</div>}<section className="panel">{loading?<Loading/>:<DataTable items={items} columns={Object.keys(items[0]||{})}/>}</section>{show&&<CreateModal title={title} endpoint={endpoint} fields={fields} onClose={()=>setShow(false)} onCreated={()=>{setShow(false);load()}}/>}</>}
function CreateModal({title,endpoint,fields,onClose,onCreated}){const {register,handleSubmit}=useForm(); const [error,setError]=useState('');const submit=async data=>{Object.keys(data).forEach(k=>{if(data[k]==='')delete data[k]; if(['course_id','teacher_id','student_id','group_id','amount','monthly_fee','max_students','duration_months'].includes(k)&&data[k]!==undefined)data[k]=Number(data[k])});try{await api.post(`/${endpoint}`,data);onCreated()}catch(e){setError(e.response?.data?.detail||'Saqlashda xatolik')}};return <div className="modal-bg"><form className="modal" onSubmit={handleSubmit(submit)}><div className="modal-head"><h2>Yangi {title.slice(0,-2)}</h2><button type="button" onClick={onClose}>×</button></div>{error&&<div className="alert">{error}</div>}<div className="form-grid">{fields.map(([key,label,type='text'])=><label key={key}>{label}<input type={type} {...register(key,{required:['first_name','last_name','name','phone','student_id','amount'].includes(key)})}/></label>)}</div><div className="modal-actions"><button type="button" className="ghost" onClick={onClose}>Bekor qilish</button><button>Saqlash</button></div></form></div>}
function Reports(){const [finance,setFinance]=useState(null),[attendance,setAttendance]=useState(null);useEffect(()=>{Promise.all([api.get('/reports/finance'),api.get('/reports/attendance')]).then(([f,a])=>{setFinance(f.data);setAttendance(a.data)})},[]);if(!finance)return <Loading/>;return <><Title title="Hisobotlar" text="Markazning asosiy ko‘rsatkichlari"/><div className="cards"><Metric label="Jami tushum" value={money(finance.income)} icon={CreditCard}/><Metric label="Jami xarajat" value={money(finance.expenses)} icon={Wallet}/><Metric label="Sof natija" value={money(finance.net)} icon={BarChart3}/><Metric label="Davomat" value={`${attendance.rate}%`} icon={CalendarDays}/></div></>}
function Metric({label,value,icon:Icon}){return <article className="metric"><span className="blue"><Icon/></span><div><small>{label}</small><strong>{value}</strong></div></article>}
function DataTable({items,columns}){if(!items?.length)return <div className="empty"><BookOpen size={30}/><p>Hozircha ma’lumot yo‘q</p></div>;return <div className="table-wrap"><table><thead><tr>{columns.filter(c=>!['id','created_at','updated_at'].includes(c)).slice(0,6).map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{items.map((row,i)=><tr key={row.id||i}>{columns.filter(c=>!['id','created_at','updated_at'].includes(c)).slice(0,6).map(c=><td key={c}>{typeof row[c]==='object'?String(row[c]):row[c]?.toString().replaceAll('_',' ')||'—'}</td>)}</tr>)}</tbody></table></div>}
function Loading(){return <div className="loading">Yuklanmoqda…</div>}; function Title({title,text,action}){return <div className="title"><div><h1>{title}</h1><p>{text}</p></div>{action&&<button onClick={action}><Plus size={18}/> Qo‘shish</button>}</div>}
function App(){const [user,setUser]=useState(null); const login=async(username,password)=>{const body=new URLSearchParams({username,password});const {data}=await api.post('/auth/login',body);localStorage.setItem('edu_token',data.access_token);const me=await api.get('/auth/me');setUser(me.data)};const logout=()=>{localStorage.removeItem('edu_token');setUser(null)};useEffect(()=>{if(localStorage.getItem('edu_token'))api.get('/auth/me').then(r=>setUser(r.data)).catch(logout)},[]);return <Auth.Provider value={{user,login,logout}}>{user?<Shell/>:<Login/>}</Auth.Provider>};createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
